name: 'Upload to AppDeployPro'
description: 'Uploads a build to AppDeployPro'
inputs:
  token:
    description: 'AppDeployPro access token.'
    required: true
  file:
    description: 'Path to apk/aab/ipa file.'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.file }}

